import { initSeo } from "~/lib/forked/remix-seo";

export const { getSeo, getSeoMeta, getSeoLinks } = initSeo({
	// Pass any SEO defaults for your site here.
	// If individual routes do not provide their own meta and link tags,
	// the tags generated by the defaults will be used.
	title: "chance.dev",
	siteName: "chance.dev",
	titleTemplate: "%t %s chance.dev",
	description:
		"Thoughts and experiences of a Georgian web dev in southern California",
});
