[functions]
  included_files = [
    "data/**/*.md",
    "data/**/*.mdx",
    "data/**/*.json",
    "node_modules/shiki/languages/**/*.json"
  ]

[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = '''
      public,
      max-age=31536000,
      s-maxage=31536000
    '''
